node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('dockers build/push') {
     docker.withRegistry('https://index.docker.io/v2/', 'DOCKER_HUB_ID') {
       def app = docker.build("mo29172/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
